version: '3'
networks:
  backend:
services:
  postgres:
    image: postgres
    container_name: story-squad-database
    networks:
      backend:
        aliases: 
          - database
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
    volumes:
      - ./pg/pgdata:/var/lib/postgresql/data
      - ./pg/postgres.conf:/etc/postgresql/postgresql.conf
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    restart: always
